<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UserGroupSiteMiniMaxM3.Data\UserGroupSiteMiniMaxM3.Data.csproj" />
    <ProjectReference Include="..\..\src\UserGroupSiteMiniMaxM3.Server\UserGroupSiteMiniMaxM3.Server.csproj" />
    <ProjectReference Include="..\UserGroupSiteMiniMaxM3.ServiceDefaults\UserGroupSiteMiniMaxM3.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
