<Project Sdk="Aspire.AppHost.Sdk/13.4.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UserGroupSiteGlm52.Data\UserGroupSiteGlm52.Data.csproj" />
    <ProjectReference Include="..\..\src\UserGroupSiteGlm52.Server\UserGroupSiteGlm52.Server.csproj" />
    <ProjectReference Include="..\UserGroupSiteGlm52.ServiceDefaults\UserGroupSiteGlm52.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
