<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UserGroupSiteOpus48.Data\UserGroupSiteOpus48.Data.csproj" />
    <ProjectReference Include="..\..\src\UserGroupSiteOpus48.Server\UserGroupSiteOpus48.Server.csproj" />
    <ProjectReference Include="..\UserGroupSiteOpus48.ServiceDefaults\UserGroupSiteOpus48.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
