<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UserGroupSiteFable5.Data\UserGroupSiteFable5.Data.csproj" />
    <ProjectReference Include="..\..\src\UserGroupSiteFable5.Server\UserGroupSiteFable5.Server.csproj" />
    <ProjectReference Include="..\UserGroupSiteFable5.ServiceDefaults\UserGroupSiteFable5.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
