<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UserGroupSiteQwen35.Data\UserGroupSiteQwen35.Data.csproj" />
    <ProjectReference Include="..\..\src\UserGroupSiteQwen35.Server\UserGroupSiteQwen35.Server.csproj" />
    <ProjectReference Include="..\UserGroupSiteQwen35.ServiceDefaults\UserGroupSiteQwen35.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
