<Project Sdk="Aspire.AppHost.Sdk/13.4.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UserGroupSiteGlm51.Data\UserGroupSiteGlm51.Data.csproj" />
    <ProjectReference Include="..\..\src\UserGroupSiteGlm51.Server\UserGroupSiteGlm51.Server.csproj" />
    <ProjectReference Include="..\UserGroupSiteGlm51.ServiceDefaults\UserGroupSiteGlm51.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
